# Generated by Django 6.1.1 on 2026-09-06 05:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator')], default='STUDENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], max_length=10)),
                ('ownership', models.CharField(choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private'), ('SEMI_GOVERNMENT', 'Semi-Government')], max_length=20)),
                ('campus_size', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_count', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('nirf_rank', models.IntegerField(blank=True, null=True)),
                ('avg_package_lpa', models.FloatField(blank=True, null=True)),
                ('annual_fee_lpa', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'colleges',
                'indexes': [models.Index(fields=['city', 'state'], name='colleges_city_a53998_idx'), models.Index(fields=['tier'], name='colleges_tier_acb334_idx'), models.Index(fields=['ownership'], name='colleges_ownersh_e0cade_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.college')),
            ],
            options={
                'db_table': 'college_exams',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=300, null=True)),
                ('level', models.CharField(help_text='"National" or "State"', max_length=50)),
                ('colleges', models.ManyToManyField(related_name='exams', through='api.CollegeExam', to='api.college')),
            ],
            options={
                'db_table': 'exams',
            },
        ),
        migrations.AddField(
            model_name='collegeexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('target_year', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Dream', 'Dream'), ('Target', 'Target'), ('Safety', 'Safety')], default='Target', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='api.college')),
            ],
            options={
                'db_table': 'bookmarks',
                'unique_together': {('user', 'college')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='collegeexam',
            unique_together={('college', 'exam')},
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('has_facility', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.college')),
            ],
            options={
                'db_table': 'facilities',
                'indexes': [models.Index(fields=['college'], name='facilities_college_b1de53_idx')],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('avg_package_lpa', models.FloatField()),
                ('highest_package', models.FloatField(blank=True, null=True)),
                ('placement_rate', models.FloatField(blank=True, help_text='Percentage', null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='api.college')),
            ],
            options={
                'db_table': 'placements',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['college', 'year'], name='placements_college_9d018d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('MBBS', 'MBBS'), ('BA', 'BA'), ('MA', 'MA')], max_length=10)),
                ('duration', models.IntegerField(help_text='Duration in years')),
                ('annual_fee', models.IntegerField(help_text='Annual fee in INR')),
                ('intake', models.IntegerField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.college')),
            ],
            options={
                'db_table': 'programs',
                'indexes': [models.Index(fields=['college'], name='programs_college_18bcc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'indexes': [models.Index(fields=['college'], name='reviews_college_32d2b3_idx'), models.Index(fields=['user'], name='reviews_user_id_79db63_idx')],
            },
        ),
    ]
